#!/bin/bash
#PBS -q single
#PBS -l nodes=1:ppn=1
#PBS -l walltime=0:20:00
#PBS -N pasta   
#PBS -o runpasta.out
#PBS -j oe
#PBS -A loni_selu_sys
#PBS -m abe
#PBS -M tyler.stevens@selu.edu   


module load java
module load python/3.5.2-anaconda-tensorflow
cd work/tstevens/FinalProject/output

pwd
python ~/pasta/run_pasta.py -i /data/QuercusFASTA.txt
